# Netlify configuration file for Node.js server
# For basic deployment, use the following settings

[build]
  command = "npm install && npm run build"
  publish = "public"

# Redirect all requests to your server entry point
[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200

# Set environment variables if needed
#[[headers]]
#  for = "/*"
#  [headers.values]
#    X-Frame-Options = "DENY"
